"""Emit a grammar in each generator's dialect.

Each renderer first rewrites the grammar into what its dialect can express:
FuzzingBook and ISLa get a desugared, regex-expanded grammar; Fandango keeps
the operators it understands. The rewriting is real, not a pass-through -- a
`*` reaching a FuzzingBook dict as a literal asterisk is the failure mode this
module exists to prevent.
"""

from __future__ import annotations

import json
from pathlib import Path

from .desugar import desugar, flatten_alternatives
from .diagnose import expressibility
from .ir import Alt, Feature, Grammar, Lit, Node, Ref, Regex, Repeat, Seq
from .regex_expand import RegexTooComplex, expand_regex


class RenderError(Exception):
    """This grammar cannot be expressed in the requested dialect."""


HEADER = "# Generated by SpreadEx from {source}. Edit the source, not this file."


def _prepare(g: Grammar, generator: str) -> Grammar:
    """Rewrite a grammar into the subset the target dialect can express."""
    exp = expressibility(g, generator)
    if not exp.usable:
        raise RenderError(
            f"{generator} cannot express this grammar:\n  "
            + "\n  ".join(exp.blockers)
        )
    out = g
    if Feature.REGEX_TERMINAL in exp.missing:
        out = _expand_regexes(out)
    if exp.missing - {Feature.REGEX_TERMINAL}:
        out = desugar(out)
    return flatten_alternatives(out)


def _expand_regexes(g: Grammar) -> Grammar:
    """Expand regex terminals, giving each character class its own rule.

    Inlining a class instead would splice 60-odd alternatives into every rule
    that uses it: the grammar balloons, and `r'[A-Za-z]{1,2}'` becomes
    `"A" | ... | "z" | (A|..|z)(A|..|z)`, whose shape ISLa's parser rejects.
    A shared named rule keeps it small and unambiguous:

        <IDENT> ::= <IDENT__c1> | <IDENT__c1> <IDENT__c1>
        <IDENT__c1> ::= "A" | "B" | ...
    """
    rules: dict[str, Node] = {}
    classes: dict[tuple[str, ...], str] = {}   # class contents -> rule name

    def class_rule(node: Alt, owner: str) -> Ref:
        key = tuple(o.text for o in node.options)
        if key not in classes:
            name = f"{owner}__c{len([k for k in classes if k])+1}"
            while name in g.rules or name in rules:
                name += "_"
            classes[key] = name
            rules[name] = node
        return Ref(classes[key])

    def lift_classes(node: Node, owner: str) -> Node:
        """Replace every enumerated character class with a reference."""
        if isinstance(node, Alt):
            if node.options and all(isinstance(o, Lit) and len(o.text) == 1 for o in node.options) \
                    and len(node.options) > 4:
                return class_rule(node, owner)
            return Alt(tuple(lift_classes(o, owner) for o in node.options))
        if isinstance(node, Seq):
            return Seq(tuple(lift_classes(i, owner) for i in node.items))
        if isinstance(node, Repeat):
            return Repeat(lift_classes(node.node, owner), node.min, node.max)
        return node

    for name, body in g.rules.items():
        expanded = _expand_node(body, name)
        rules[name] = lift_classes(expanded, name)
    return g.copy_with(rules)


def _expand_node(node: Node, rule: str) -> Node:
    if isinstance(node, Regex):
        try:
            return expand_regex(node.pattern)
        except RegexTooComplex as exc:
            raise RenderError(f"<{rule}>: r'{node.pattern}' cannot be enumerated: {exc}") from exc
    if isinstance(node, Seq):
        return Seq(tuple(_expand_node(i, rule) for i in node.items))
    if isinstance(node, Alt):
        return Alt(tuple(_expand_node(o, rule) for o in node.options))
    if isinstance(node, Repeat):
        return Repeat(_expand_node(node.node, rule), node.min, node.max)
    return node


def _ordered(g: Grammar) -> list[str]:
    """Start first, then every other rule in definition order."""
    names = [g.start] + [n for n in g.rules if n != g.start]
    return [n for n in names if n in g.rules]


# ------------------------------------------------------------- FuzzingBook

def render_fuzzingbook(g: Grammar, source: str = "a SpreadEx grammar") -> str:
    """A Python module defining GRAMMAR, as FuzzingBook expects."""
    prepared = _prepare(g, "fuzzingbook")
    lines = [
        HEADER.format(source=source),
        "",
        "# Already plain BNF: every EBNF operator has been desugared into rules.",
        "# Do NOT run fuzzingbook's convert_ebnf_grammar() over this -- it would",
        "# read a literal '+', '*' or '?' following a <nonterminal> as an operator.",
        "# A JavaScript '<identifier>++;' would silently become 'one or more",
        "# identifiers, then +;'.",
        "SPREADEX_PURE_BNF = True",
        "",
        "GRAMMAR = {",
    ]
    for name in _ordered(prepared):
        alts = prepared.alternatives(name)
        rendered = ", ".join(json.dumps(_flat_string(a, name)) for a in alts)
        lines.append(f"    {json.dumps(f'<{name}>')}: [{rendered}],")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def get_grammar():")
    lines.append("    return GRAMMAR")
    return "\n".join(lines) + "\n"


def _flat_string(node: Node, rule: str) -> str:
    """A FuzzingBook alternative is one flat string of literals and <refs>."""
    if isinstance(node, Lit):
        return node.text
    if isinstance(node, Ref):
        return f"<{node.name}>"
    if isinstance(node, Seq):
        return "".join(_flat_string(i, rule) for i in node.items)
    raise RenderError(
        f"<{rule}>: FuzzingBook alternatives must be flat; found {type(node).__name__}. "
        f"This is a desugaring bug -- please report it."
    )


# --------------------------------------------------------------------- ISLa

def render_isla(g: Grammar, source: str = "a SpreadEx grammar") -> str:
    """Plain BNF, which is what ISLa's `solve` reads."""
    prepared = _prepare(g, "isla")
    lines = [HEADER.format(source=source), ""]
    for name in _ordered(prepared):
        alts = prepared.alternatives(name)
        head = f"<{name}> ::= "
        pad = " " * (len(head) - 2)
        lines.append(head + _bnf_alt(alts[0], name))
        for alt in alts[1:]:
            lines.append(f"{pad}| " + _bnf_alt(alt, name))
        lines.append("")
    return "\n".join(lines)


def _bnf_alt(node: Node, rule: str) -> str:
    if isinstance(node, Lit):
        return _quote(node.text)
    if isinstance(node, Ref):
        return f"<{node.name}>"
    if isinstance(node, Seq):
        return " ".join(_bnf_alt(i, rule) for i in node.items)
    raise RenderError(
        f"<{rule}>: BNF alternatives must be flat; found {type(node).__name__}. "
        f"This is a desugaring bug -- please report it."
    )


def _quote(text: str) -> str:
    escaped = (text.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r"))
    return f'"{escaped}"'


# ----------------------------------------------------------------- Fandango

def render_fandango(g: Grammar, source: str = "a SpreadEx grammar",
                    constraints: str | None = None) -> str:
    """Fandango `.fan`: BNF plus the EBNF operators it understands."""
    prepared = _prepare(g, "fandango")
    lines = [HEADER.format(source=source), ""]
    for name in _ordered(prepared):
        alts = prepared.alternatives(name)
        rendered = [_fan_alt(a) for a in alts]
        one_line = f"<{name}> ::= " + " | ".join(rendered)
        if len(one_line) <= 100 or len(rendered) == 1:
            lines.append(one_line)
        else:
            # Fandango accepts alternatives on one line, or wrapped in
            # parentheses. It rejects both leading-pipe and trailing-pipe
            # continuation lines, so long rules must be parenthesised.
            lines.append(f"<{name}> ::= (")
            for i, alt in enumerate(rendered):
                suffix = " |" if i < len(rendered) - 1 else ""
                lines.append(f"  {alt}{suffix}")
            lines.append(")")
        lines.append("")
    if constraints:
        lines.append(constraints.strip())
        lines.append("")
    return "\n".join(lines)


def _fan_alt(node: Node, parenthesize: bool = False) -> str:
    if isinstance(node, Lit):
        return _quote(node.text)
    if isinstance(node, Regex):
        return f"r'{node.pattern}'"
    if isinstance(node, Ref):
        return f"<{node.name}>"
    if isinstance(node, Seq):
        body = " ".join(_fan_alt(i, parenthesize=True) for i in node.items)
        return f"({body})" if parenthesize else body
    if isinstance(node, Alt):
        body = " | ".join(_fan_alt(o) for o in node.options)
        return f"({body})"
    if isinstance(node, Repeat):
        inner = _fan_alt(node.node, parenthesize=True)
        if (node.min, node.max) == (0, 1):
            return f"{inner}?"
        if (node.min, node.max) == (0, None):
            return f"{inner}*"
        if (node.min, node.max) == (1, None):
            return f"{inner}+"
        if node.max is None:
            return f"{inner}{{{node.min},}}"
        if node.min == node.max:
            return f"{inner}{{{node.min}}}"
        return f"{inner}{{{node.min},{node.max}}}"
    raise RenderError(f"cannot render {type(node).__name__} for Fandango")


# ------------------------------------------------------------------- ANTLRv4

def render_antlr(g: Grammar, source: str = "a SpreadEx grammar",
                 name: str | None = None) -> str:
    """ANTLRv4, which is what Grammarinator consumes.

    Everything is emitted as a PARSER rule (lowercase initial) with terminals
    inline as literals. ANTLR forbids a lexer rule from referencing a parser
    rule, and a grammar written in another notation has no such separation, so
    keeping it all on one side is the only mapping that cannot produce an
    invalid grammar.
    """
    from .antlr import antlr_rule_name, escape_antlr_literal

    prepared = _prepare(g, "grammarinator")
    taken: dict[str, str] = {}
    # Name the start rule first so it keeps the cleanest spelling.
    for rule in _ordered(prepared):
        antlr_rule_name(rule, taken)

    grammar_name = _antlr_grammar_name(name or source)
    lines = [f"// {HEADER.format(source=source)[2:]}", "",
             f"grammar {grammar_name};", ""]
    for rule in _ordered(prepared):
        alts = prepared.alternatives(rule)
        rendered = [_antlr_alt(a, taken, escape_antlr_literal) for a in alts]
        head = f"{taken[rule]} : "
        one_line = head + " | ".join(rendered) + " ;"
        if len(one_line) <= 100 or len(rendered) == 1:
            lines.append(one_line)
        else:
            lines.append(head.rstrip())
            for i, alt in enumerate(rendered):
                prefix = "      " if i == 0 else "    | "
                lines.append(f"{prefix}{alt}")
            lines.append("    ;")
    lines.append("")
    return "\n".join(lines)


def _antlr_grammar_name(source: str) -> str:
    import re as _re

    stem = Path(source).stem if "/" in source or "." in source else source
    cleaned = _re.sub(r"[^A-Za-z0-9_]", "_", stem) or "Generated"
    if not cleaned[0].isalpha():
        cleaned = "G" + cleaned
    return cleaned[0].upper() + cleaned[1:]


def _antlr_alt(node: Node, taken: dict[str, str], escape, parenthesize: bool = False) -> str:
    if isinstance(node, Lit):
        # ANTLR has no empty literal; an empty alternative is just nothing.
        return "" if node.text == "" else f"'{escape(node.text)}'"
    if isinstance(node, Regex):
        raise RenderError(
            f"ANTLR output cannot carry the regex terminal r'{node.pattern}'. "
            f"This is a preparation bug -- please report it."
        )
    if isinstance(node, Ref):
        return taken.get(node.name, node.name)
    if isinstance(node, Seq):
        body = " ".join(x for x in
                        (_antlr_alt(i, taken, escape, True) for i in node.items) if x)
        return f"({body})" if parenthesize and len(node.items) > 1 else body
    if isinstance(node, Alt):
        return "(" + " | ".join(_antlr_alt(o, taken, escape) for o in node.options) + ")"
    if isinstance(node, Repeat):
        inner = _antlr_alt(node.node, taken, escape, True) or "()"
        if (node.min, node.max) == (0, 1):
            return f"{inner}?"
        if (node.min, node.max) == (0, None):
            return f"{inner}*"
        if (node.min, node.max) == (1, None):
            return f"{inner}+"
        # ANTLR has no {m,n}: write it out.
        parts = []
        hi = node.max
        for count in range(node.min, hi + 1):
            parts.append(" ".join([inner] * count) if count else "")
        return "(" + " | ".join(parts) + ")"
    raise RenderError(f"cannot render {type(node).__name__} for ANTLR")


RENDERERS = {
    "fuzzingbook": render_fuzzingbook,
    "isla": render_isla,
    "fandango": render_fandango,
    "grammarinator": render_antlr,
}

EXTENSIONS = {"fuzzingbook": ".py", "isla": ".bnf", "fandango": ".fan",
              "grammarinator": ".g4"}


def render(g: Grammar, generator: str, source: str = "a SpreadEx grammar") -> str:
    try:
        renderer = RENDERERS[generator]
    except KeyError:
        supported = ", ".join(sorted(RENDERERS))
        raise RenderError(
            f"No renderer for {generator!r}. SpreadEx can emit: {supported}.\n"
            f"  Grammarinator needs ANTLRv4 (.g4), which is not emitted yet."
        ) from None
    return renderer(g, source)
